UPDATE TIPOLOGICA_CAMPI_DINAMICI SET REGEX = '^[0-9]{10}$' WHERE TIPO_DATI LIKE '%CELLULARE%';

UPDATE TIPOLOGICA_CAMPI_DINAMICI SET REGEX = '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$' WHERE TIPO_DATI LIKE '%MAIL%' OR TIPO_DATI LIKE '%PEC%';