import type { Piattaforma } from "../types/types";

export const mockPiattaforme: Piattaforma[] = [
    {
        id: 1,
        nome: "PCC",
        descrizione: "Piattaforma Certificazione Crediti",
        url: "https://pcc.mef.gov.it",
        canale: "PORTALE",
        objClass: "pccPlatform",
        readOnly: false,
        codiceIct: "PCC_SOGEI",
        oamMetadataName: "oam:clientId",
        oamMetadataValue: "pcc-client",
        richiedibileDaCruscotto: true,
        richiedibileInCorso: false,
        ripetibile: false,
        utilizzoModelloAutorizzativo: false,
        abilitazione: "TICKET"
    },
    {
        id: 2,
        nome: "FDI",
        descrizione: "Fondo di Investimento",
        url: "",
        canale: "PORTALE",
        objClass: "fdiPlatform",
        readOnly: false,
        codiceIct: "",
        oamMetadataName: "",
        oamMetadataValue: "",
        richiedibileDaCruscotto: false,
        richiedibileInCorso: false,
        ripetibile: false,
        utilizzoModelloAutorizzativo: false,
        abilitazione: "VERTICALE"
    },
    {
        id: 3,
        nome: "LEASING",
        descrizione: "Gestione contratti di leasing",
        url: "",
        canale: "PORTALE",
        objClass: "leasingPlatform",
        readOnly: false,
        codiceIct: "",
        oamMetadataName: "",
        oamMetadataValue: "",
        richiedibileDaCruscotto: false,
        richiedibileInCorso: false,
        ripetibile: false,
        utilizzoModelloAutorizzativo: false,
        abilitazione: "TICKET"
    },
    {
        id: 4,
        nome: "MUTUI",
        descrizione: "Gestione mutui",
        url: "",
        canale: "PORTALE",
        objClass: "mutuiPlatform",
        readOnly: true,
        codiceIct: "",
        oamMetadataName: "",
        oamMetadataValue: "",
        richiedibileDaCruscotto: false,
        richiedibileInCorso: false,
        ripetibile: false,
        utilizzoModelloAutorizzativo: false,
        abilitazione: "TICKET"
    },
    {
        id: 5,
        nome: "CARTE",
        descrizione: "Gestione carte di pagamento",
        url: "",
        canale: "PORTALE",
        objClass: "cartePlatform",
        readOnly: false,
        codiceIct: "",
        oamMetadataName: "",
        oamMetadataValue: "",
        richiedibileDaCruscotto: false,
        richiedibileInCorso: false,
        ripetibile: false,
        utilizzoModelloAutorizzativo: false,
        abilitazione: "VERTICALE"
    }
];
